COPYING
set-wallpaper-contract/set-wallpaper.vala
src/Cache.vala
src/Translations.vala
src/Views/Dock.vala
src/Views/HotCorners.vala
src/desktop-plug.vala

resolve license issues

---

set-wallpaper-contract/CMakeLists.txt

Fix build with cmake 3.8

---

src/Views/HotCorners.vala

Custom command revealer

---

set-wallpaper-contract/set-wallpaper.vala
src/Views/Wallpaper.vala

Reset color shading type on wallpaper change

---

CMakeLists.txt
data/io.elementary.switchboard.plug.desktop.gschema.xml
src/Views/Wallpaper.vala
src/desktop-plug.vala

Save wallpaper source state

---

src/Widgets/WallpaperContainer.vala

Use the newly introduced Granite.AsyncImage to asynchronously load the image to an image in the UI. This noticeably speeds up loading of the plug because the main thread is no longer blocked by rendering the image.

Load wallpapers using Granite.AsyncImage

---

README.md

List of dependencies require to build the project. Mostly copied from [switchboard-plug-power](https://github.com/elementary/switchboard-plug-power)

Add Dependency List to README

---

src/Views/HotCorners.vala
src/Views/Wallpaper.vala

Replaces one margin with column spacing, replace a margin_left with margin_start

Fix deprecated margins

---

src/GalaSettings.vala

Removes a bunch of unused settings and bumps the copyright header

Remove unused Gala settings

---

src/Views/Wallpaper.vala
src/Widgets/WallpaperContainer.vala

Fixes #68 
Sets menuitem insensitive when we don't have permission, just like Files

Trash wallpapers

---

src/desktop-plug.vala

Don't create dock page if no plank

---

meson.build
src/Views/Dock.vala
src/meson.build

This API change happened in Freya

Drop old plank support

---

src/Views/Wallpaper.vala

Remove non-existant setting

---

data/plug.css

Since the goal is to not have app-specific CSS in the system stylesheet

Add hotcorner CSS from system stylesheet

---

src/Views/Appearance.vala

Switch to ModeButton for text size

---

src/Views/Wallpaper.vala

Wallpaper: Use FileChooserNative

---

src/desktop-plug.vala

Follows https://github.com/elementary/switchboard/wiki/System-Settings-Schema-Specification

Update for wallpaper settings deprecation

---

set-wallpaper-contract/set-wallpaper.vala
src/Views/Wallpaper.vala

Instead of relying on an Ubuntu-patch
Fixes  #172

Use the interfaces provided by LightDM

---

set-wallpaper-contract/set-wallpaper.vala
src/Views/Wallpaper.vala

Chmod 0604 copy of wallpaper for greeter

---

src/Plug.vala

Plug: Add a11y search strings

---

data/io.elementary.switchboard.pantheon-shell.appdata.xml.in
src/Views/Wallpaper.vala

Wallpaper: Only copy if not in ANY backgrounddirs

---

data/io.elementary.switchboard.pantheon-shell.appdata.xml.in

For better display in Feedback and AppCenter

AppData: Add "Settings" to name

---

src/IOHelper.vala
src/PantheonAccountsServicePlugin.vala
src/Plug.vala
src/ThumbnailGenerator.vala
src/Views/Appearance.vala
src/Views/Dock.vala
src/Views/HotCorners.vala
src/Views/Wallpaper.vala
src/Widgets/SolidColorContainer.vala
src/Widgets/WallpaperContainer.vala

Fixes #229
Prevents conflicts with other plugs that use classes with the same name.

Add PantheonShell namespace to all classes

---

po/POTFILES
src/Plug.vala
src/Views/Multitasking.vala
src/meson.build

As discussed in a call. Gives us a handy new home for anything related to Gala behavior.

HotCorners: Rename to Multitasking

---

src/Views/Multitasking.vala

Multitasking: Add auto workspace behavior switches

---

src/Views/Appearance.vala

I was gonna use a ScrolledWindow here (hence the branch name), but wasn't happy with the results with the stack switcher up top. So instead, this just adds a bottom margin ~and improves code style a tiny bit~.

Appearance: Add bottom margin

---

src/Plug.vala
src/Views/Appearance.vala
src/Views/Dock.vala
src/Views/Multitasking.vala

Move switches from appearance to other tabs

---

po/POTFILES
src/Plug.vala
src/Views/Appearance.vala
src/Views/Text.vala
src/meson.build

#291 and #295 seem to be a little stuck. Trying to restart progress here by going smaller pieces at a time.
This does the least to move text settings from the Appearance page into their own page as in #295

Move Text settings to their own page

---

src/Views/Text.vala

Color dyslexia-friendly switch

---

src/Views/Wallpaper.vala

Add timestamp to filename

---

set-wallpaper-contract/set-wallpaper.vala

Fixes #320 when using "Set as Desktop Background" in Files

Add timestamp to filename in contract

---

data/check.svg
data/icons.gresource.xml
data/plug.css
src/Widgets/WallpaperContainer.vala

Closes #274 
Uses radio button instead of icon

Selected wallpaper check: follow accent color

---

src/Views/Wallpaper.vala

Closes #111 
Also, now removed wallpapers are not completely deleted, but trashed instead

Undo mechanism for trashing wallpapers

---

src/Views/Appearance.vala

Appearance: Reorder connection of signals

---

src/Views/Multitasking.vala

Requires https://github.com/elementary/gala/pull/1614
Fixes #184

Add previous/next workspace to hot corners

---

src/Views/Wallpaper.vala

Mark "Dim with dark style:" string as translatable

---

debian/control

For wallpaper syncing to Greeter

Control: add runtime depends on Settings Daemon to 1.3.0

---

set-wallpaper-contract/meson.build
set-wallpaper-contract/set-wallpaper.vala
src/Views/Wallpaper.vala
src/WallpaperOperation.vala
src/meson.build

Fixes #217
Create a new namespace `WallpaperOperation` to avoid duplicated code.

Make sure only copy wallpapers if not in ANY backgrounddirs

---

src/Widgets/WallpaperContainer.vala

GTK4 prep. Rewrite the context menu using a GLib.Menu and event controller. There's no Gtk.Menu in GTK4 so doing it this way it's basically a drop in replacement for Gtk.PopoverMenu. And use event controller because there's no eventbox

WallpaperContainer: Use GLib.Menu and Gtk.GestureMultiPress

---

src/Views/Wallpaper.vala

* Bump copyright header
* Subclass box instead of grid
* Code style
* Use child property
* explicit margins and expands
* Can't pack widgets into filechooser portal

Wallpaper: Gtk4 prep

---

src/Plug.vala
src/Views/Appearance.vala

We support this in the stylesheet so might as well expose the setting

Appearance: Always Show Scrollbars setting

---

README.md
meson.build
src/Views/Wallpaper.vala

Replace deprecated signal. Deleting wallpapers sometimes doesn't work without this because the old signal is only sent sometimes

Wallpaper: use Toast.dismissed

---

src/Plug.vala

Don't test for the presence of Plank to display this settings pane. We already check in the pane for relevant settings

Fix missing Dock & Panel settings

---

src/Views/Appearance.vala

Gives these radios some context

Appearance: improve screenreader a11y for lists of radios

---

src/Views/Appearance.vala

Fixes https://github.com/elementary/gala/issues/956

Set preferred color theme for mutter

---

src/Views/Appearance.vala

https://github.com/elementary/gala/pull/2033

Use new animations schema

---

src/Views/Multitasking.vala

https://github.com/elementary/gala/pull/2034

Use new behavior schema

---

data/desktop.metainfo.xml.in
meson.build

Release 8.0.1

---

src/Plug.vala

I opted to use the description text rather than title text because it seems better for including the right search keywords

Plug: add panel scroll to search results

---

src/Views/Text.vala

Vertical Align SpinButton

---

src/Views/Multitasking.vala

HotcornerControl/CustomCommand: Fix infinite loop

---

data/desktop.metainfo.xml.in
meson.build

Release 8.2.0
