elementary/settings-desktop

- src/Views/Wallpaper.vala
Fix #40 .
On a fresh installation of elementary the `/home/<user>/.local/share/backgrounds/` directory may not exist. Ensure we create it, otherwise we end up not being able to set the background to a custom one the user chooses because the subsequent copy to that directory fails.
> Create local background directory if necessary

- debian/switchboard-plug-pantheon-shell.install
- set-wallpaper-contract/CMakeLists.txt
- set-wallpaper-contract/set-wallpaper.contract.in
Fix #6. Install set-wallpaper binary to /usr/libexec/switchboard-plug-pantheon-shell.
> Fix set-wallpaper binary location

- set-wallpaper-contract/CMakeLists.txt
pkg-config doesn't know about the non-existent "posix" module, so it exits and complains it doesn't exist.
The posix dependency needs to be present only in the CMake function "vala_precompile".
> set-wallpaper-contract/CMakeLists.txt: fix posix dependency

- src/GalaSettings.vala
For now we don't need these settings, as the code doesn't use any of these properties and sets them manually through the `schema` in this settings object. With these Granite also throws warnings like:
`g_variant_get_int32: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT32)' failed`
> Fix get int32 warnings

- src/Cache.vala
- src/desktop-plug.vala
Fixes `gee_abstract_map_clear: assertion 'self != NULL' failed` warnings and improves performance by removing redundant usage of `compute_key` multiple times for the same uri. Makes constructing paths and filenames use native `GLib` methods.
> Fix gee_abstract_map_clear warnings; improve performance

- src/desktop-plug.vala
Stack switchers no longer have homogeneous button widths by default in 3.22
> Make stack switcher homogeneous

- set-wallpaper-contract/set-wallpaper.vala
Fixes #4.
When setting a wallpaper with the contract, if the picture options have been set to `none` (i.e. after a solid color has been applied), nothing happened before. This resets the key to default to allow the wallpaper to show.
> Reset picture options if a solid color has been set

- src/Views/Wallpaper.vala
> Stop the currently selected wallpaper being unchecked when reselecting

- .travis.yml
- debian/control
- src/CMakeLists.txt
- src/Widgets/WallpaperContainer.vala
Fixes #81 
Currently the tooltip only displays for the wallpapers that have an artist tag set. Not sure if that's the correct behavior and whether or not the tooltip should always show. If so, what information should appear?
> Display artist data in tooltip

- src/Widgets/WallpaperContainer.vala
Fixes #78 
Thumbnails show now be back to the previous size before switching to tumbler for thumbnails.
> Revert size to 162x100

- src/CMakeLists.txt
- src/IOHelper.vala
- src/Views/Wallpaper.vala
A follow up to https://github.com/elementary/switchboard-plug-pantheon-shell/pull/50, but without changing anything in the UI or behaviour. 
A preparation for https://github.com/elementary/switchboard-plug-pantheon-shell/issues/32.
* IOHelper in a separate file
* Let warning () format the warning string
* Make some methods static that didn't use anything from the instance
* Constant name to `UPPER_CASE`
* Code simplifications
* Remove unneded Gtk main iteration call
* Fix code style
> Refactor Wallpaper.vala v2

- src/Widgets/WallpaperContainer.vala
Fixes #90.
This fixes an incorrect usage of the width and height parameters of `set_from_file_async` to `Granite.AsyncImage`, this API already takes care of the scale factor.
> Fix HiDPI thumb sizes

- src/Views/Wallpaper.vala
This fixes a bug where after drag and drop you can't remove the new wallpaper without closing and reopening Switchboard.
On line 466 we create a new file from URI instead of using the existing file because we want to make sure we're deleting the copied file that lives in `.local/share`, not the original file
> Dry add wallpaper

- src/Views/Wallpaper.vala
Fixes #157 
The issue was actually here (with using `get_path` instead of `get_uri`):
https://github.com/elementary/switchboard-plug-pantheon-shell/blob/master/src/Views/Wallpaper.vala#L359
But... since everything is already a path and we're doing stuff to convert it to a URI, why not just use a path throughout.
> Use file paths instead of URIs for wallpaper folders

- data/meson.build
- meson.build
- set-wallpaper-contract/meson.build
- src/meson.build
On NixOS all packages are installed into their own immutable prefix.
Because of this switchboard_dep.get_pkgconfig_variable will return a
path from within switchboard's prefix and we cannot write to it.
By using define_variable we can replace the libdir to be from the
paths from meson. This should have no affect on elementaryOS.
>  build: fix install path for switchboard plug

- .github/workflows/main.yml
This change also runs `ninja install` after `ninja`, and sets the `DESTDIR` variable so no unwanted side effects happen and things get installed into an isolated directory (`/build/out`).
> run installation in CI

- set-wallpaper-contract/set-wallpaper.vala
- src/Views/Wallpaper.vala
Previously the system backgrounds directory was
hardcoded to /usr/share/backgrounds. We now build
paths from entries in system_data_dirs which on elementary OS
should still be /usr/share/backgrounds. This was problematic
for us in NixOS because we break FHS, meaning /usr/share doesn't
exist. However we still set XDG_DATA_DIRS to include our path
/run/current-system/sw/share, so using GLib.get_system_data_dirs
and building paths from those entries should allow compatibility.
Please also note, for compatibility reasons it's almost always
a good idea to go this route.
Fixes #166
---
1. Run with `G_MESSAGES_DEBUG=all` and see it loads the correct system background directory
2. Are there backgrounds in the plug?
I'm not sure what's being done for `update_accountsservice ()` so I wasn't sure …
> Get system background directories from XDG_DATA_DIRS

- debian/control
There are currently no settings that rely on the applications menu, so it doesn't make sense to have this depends
> Remove applications-menu dep

- data/plug.css
- src/Views/Appearance.vala
* It doesn't really save any work to set tooltip_text inside the colorbutton class. It's just a one-liner so you're doing extra work here.
* I think having one more instance of GLib.Settings is probably better than reading the setting once per color. Ram is probably cheaper than IO
* You can assign `group` directly from the `object()` method
* `unowned style_context`
> A few optimizations

- src/Views/Appearance.vala
I've been having some issues where I open the plug and then all the sudden I get switched to another accent. This seems to fix that
> Appearance: avoid an unintentional accent change

- set-wallpaper-contract/set-wallpaper.contract.in
I checked all the common image types for compatibility. BMP, GIF, JPEG, PNG, TIFF work without any problems. SVG works, but looks rather ugly (I imagine the render is scaled form the view box, not the view box itself). This solves the problem in #131, DjVU files no longer can be set as background, only image files with types mentioned above.
> Use a selection of image MIME types instead of general image type

- README.md
- src/Views/Appearance.vala
This PR adds a toggle to enable dyslexic-friendly system wide fonts to the Appearance switchboard, as discussed in https://github.com/elementary/switchboard-plug-pantheon-shell/issues/234).
Default behaviour:
And once enabled:
> Option to enable dyslexia-friendly text

- src/Views/Appearance.vala
Related to https://github.com/elementary/gala/pull/863
> Schedule dark mode

- src/Views/Appearance.vala
This keeps blue at the beginning, but rotates the rainbow around it so they're in a more natural order. Alternative to #245.
If this is merged, we should update:
> Appearance: Re-order Accent Colors

- src/Plug.vala
I realized we missed these. This will make them more discoverable in search from the Applications Menu and the Switchboard search.
> Plug: Add dark style and accent to search results

- src/Views/Dock.vala
Fixes #257 
Ensure that we set the sensitivity on this switch when the view is constructed and not just when settings change
> Views/Dock: set pressure hide sensitivity on construct

- src/Views/Appearance.vala
It was centered on the line, now it's left-aligned like everything else. Changed the margin to use modern code style while here.
> Appearance: Fix alignment of accent help label

- src/Views/Appearance.vala
- src/Views/Dock.vala
- src/Views/Multitasking.vala
Fixes #267 
I'm not sure what margin I should use from the edge of the window. The HIG seems to say minimum 12 px, which is what I used. (This increased the dock panel padding from 6 px.) But elsewhere in switchboard, there's both 12 px and 24 px. I'm not sure which to use, or if there's a convention I'm missing here. So let me know if I should change the value, it should be pretty easy 🙂️
Also, a question this brought about. Should we have a more standard padding in switchboard? I'd be happy to make a bunch of PRs to standardize other pages to the same value if we want. Let me know.
> Add padding to appearance, dock, multitasking views

- src/Views/Appearance.vala
I realized we never updated this since we initially intended it to only affect system components. This copy helps clarify that apps _may_ follow it, and leans into it being a preference more than a forced setting.
Alternate copy suggestions welcome, but I do think it needs to be updated (see: https://github.com/elementary/stylesheet/issues/1057)
> Appearance: Mention apps in dark style copy

- data/plug.css
I guess colorAccent is from old stylesheet
> Fix accent color for focused wallpaper

- src/Views/Appearance.vala
I'm not super attached to this PR, it was more to see if `bind_with_mapping` made sense here. The benefit this has is that it's a property bind instead of relying on a specific interaction signal and it's bidirectional so changing the setting externally will update the radios
> Appearance: bind radios with mapping

- debian/control
Since we're now using a couple of settings keys that were introduced in the latest gala, make sure to bump the runtime dep
> Bump Gala depends to 7.0.2

- set-wallpaper-contract/Config.vala.in
- set-wallpaper-contract/meson.build
- set-wallpaper-contract/set-wallpaper.vala
The delay value is not shown as translated (in this case `1 hour`).
The delay value is shown as translated (in this case `1 hour` is translated to `1時間` in Japanese)
> set-wallpaper: Fix delay value not shown as translated

- src/Plug.vala
- src/Views/Wallpaper.vala
When you remove a wallpaper and immediately close the switchboard, the wallpaper won't be removed. This PR fixes this.
> Wallpaper: Confirm wallpaper removal when hidden

- src/Views/Dock.vala
In the interest of #96 
The a11y indicator setting is the only setting that now only exists in the a11y plug, so this completes the "a11y features are just features" project along with https://github.com/elementary/switchboard-plug-keyboard/pull/446
> Dock: add checks for panel indicators

- .github/workflows/main.yml
- README.md
- set-wallpaper-contract/meson.build
- set-wallpaper-contract/set-wallpaper.vala
set-wallpaper-contract can be ported to GTK 4 because its source is separated from the plug itself which is not ported to GTK 4 yet
> set-wallpaper-contract: Port to GTK 4

- src/Views/Wallpaper.vala
Previously before the fix, the wallpaper cannot be changed via settings because it only sets the wallpaper for the light theme, not the dark theme. This fixes the issue.
> fix(wallpaper): change wallpaper for dark theme settings

- data/appearance-dark.svg
- data/appearance-default.svg
- data/plug.css
- src/Views/Appearance.vala
Changes from #377 
* Use light/dark style images from Onboarding and use your wallpaper
* Create them in a way that's more compatible with GTK 4 and relying on CSS for sizing
* Replace grid with box
* set mnemonic widget
> Appearance: GTK4 prep

- src/Views/Dock.vala
Better wording would be appreciated :)
elementary/wingpanel#567
> Dock/Panel: Add setting for scroll to switch workspaces

- src/Views/Appearance.vala
We had a separate WM key and didn't set this one historically because there was a GTK bug that caused revealers to reserve extra blank space when animations were disabled. That bug appears to be fixed, so this massively increases the amount of animations that are disabled
Looks like we can't use bind with two settings objects? So that's why I switched to a property notify instead of bind with `SET`
> Appearance: get/set animations from interface key

- src/Views/Appearance.vala
According to GTK docs, this is the proper way and connecting to Toggled is discouraged
> Appearance: use stateful action for radios

- data/desktop.metainfo.xml.in
- src/Views/Multitasking.vala
> Multitasking: show apps menu hotcorner at the same corner as panel

- data/desktop.metainfo.xml.in
- src/Views/Appearance.vala
Fixes #429 
Rebase merge/review commits separately
* Bind color scheme radios to color scheme gsetting with create_action
* Bind dark schedule radios to dark schedule gsetting with create_action
Removes a bunch of complicated touching of accounts service and simplifies settings binding. When manually changing color scheme while schedule is enabled, schedule will be snoozed instead of changed to disabled. Settings Daemon now handles setting mutter settings, syncing accountsservice etc
> Appearance: use settings.create_action
